[units]          
angle = 'deg'        # Units used for angles
length = 'mm'        # units used for lengths

[panel]              # Panel parameters
number = 12          # number of panels in  the arena
omitted = []         # list  of omitted panels
offset_angle = 0     # offset angle for panel position
width = 40.5         # width of panels 
depth = 15           # depth from front to back of panels 

[pins]               # Header pin parameters
number = 15          # number of header pins
pitch = 2.54         # pitch (distance) between header pins
depth = 12.1         # depth from front to header pins 
omitted = []         # pins omitted from header



